name: 'training_project'
version: '1.0.0'
config-version: 2

profile: 'training_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  training_project:
    +materialized: table
    stg:
      +materialized: table
