# Place this file at ~/.dbt/profiles.yml  (or set DBT_PROFILES_DIR to this folder)
training_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      user: "{{ env_var('PGUSER', 'db_user') }}"
      password: "{{ env_var('PGPASSWORD', 'db_pass') }}"
      dbname: "{{ env_var('PGDATABASE', 'analytics') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'stg') }}"
      port: {{ env_var('PGPORT', '5432') | int }}
      threads: {{ env_var('DBT_THREADS', '4') | int }}
      keepalives_idle: 0
      connect_timeout: 10
